name: Build and deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.2

      - name: Compile tex file into pdf
        uses: dante-ev/latex-action@latest
        with:
          entrypoint: ./scripts/build

      - uses: actions/upload-artifact@v4
        with:
          name: Master thesis
          path: main.pdf
