name: Build and deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.2

      - name: Compile tex file into pdf
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          extra_fonts: |
            ./fonts/EB_Garamond/*.otf
            ./fonts/Lato/*.ttf
            ./fonts/Source_Code_Pro/*.ttf
        
      - uses: actions/upload-artifact@v4
        with:
          name: Master thesis
          path: main.pdf
